name: Gearoid O'Connor
exclude: ["node_modules", "gulpfile.js", "package.json"]

markdown: kramdown
pygments: true
permalink: /:title
title: Qiu Feng
url: /
highlighter: rouge
author_info: <a href="www.qiufeng.me">Qiu Feng</a>


##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "the epicenter of change. --- 2015"
  - text: "Write the Code. Change the world. --- 2014"
  - text: "A whole new world is developing. --- 2013"
  - text: "Where great ideas go on to do great things. --- 2012"

background-img: "../img/intro-bg.jpg"